# Numpy 1D Array

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])# Create a numpy array
a

array([0, 1, 2, 3, 4])

In [2]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [3]:
# Check the type of the array

type(a)

numpy.ndarray

In [4]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

In [5]:
a[0] = 100# Assign the first element to 100
a

array([100,   1,   2,   3,   4])

In [6]:
# Slicing the numpy array

d = a[1:4]
d

array([1, 2, 3])

In [7]:
select = [0, 2, 3]# Create the index list
d =a[select]# Use List to select elements
d

array([100,   2,   3])

In [9]:
# Assign the specified elements to new value

a[select] = 100000
a

array([100000,      1, 100000, 100000,      4])

In [10]:
a.size# Get the size of numpy array

5

In [11]:
a.ndim# Get the number of dimensions of numpy array

1

In [12]:
# Get the mean of numpy array

mean = a.mean()
mean

60001.0

In [13]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

48988.57011997799

In [14]:
max_a = a.max()# Get the biggest value in the numpy array
max_a

100000

In [15]:
min_a = a.min()# Get the smallest value in the numpy array
min_a

1

# Array Addition

In [3]:
u = np.array([1, 0])
v = np.array([0, 1])
z = u + v
z

array([1, 1])

# Array Multiplication

In [17]:
z = u * v
z

array([0, 0])

In [4]:
z=2*u
z

array([2, 0])

# Dot Product

In [18]:
np.dot(u, v)

0

# Mathematical Functions

In [22]:
np.pi


3.141592653589793

In [23]:
y = np.sin(a)
y

array([ 0.0357488 ,  0.84147098,  0.0357488 ,  0.0357488 , -0.7568025 ])

In [24]:
#Linspace
np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

# Numpy 2D Arrays

In [25]:
import numpy as np
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [27]:
# Every element is the same type
A = np.array(a)# Convert list to Numpy Array
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [28]:
# Show the numpy array dimensions

A.ndim

2

In [29]:
# Show the numpy array shape

A.shape

(3, 3)

In [30]:
# Show the numpy array size

A.size

9

In [31]:
# Access the element on the second row and third column

A[1, 2]


23

In [32]:
A[1][2]

23

In [33]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [34]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [37]:
X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [38]:
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [39]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [40]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [41]:
A.T

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])